from __main__ import *
import GseosIni, GseosBlocks
import GseosDecoder
import GseosMonitor
import Gseos
from GseosConversion import signed16
import time

### FTF_OUT_CMD.StopDecoder( 'CreateLM' )

def fLM_OUT_CMD(oBlock):
	"Generated by fLM_OUT_CMD"
	"""
	if( oBlock.Data[0] != 0x45 ):
	    return 
	"""

	oDest = LM_OUT_CMD

	len = oBlock.IP_Length ;

	oDest.Block[0:len] = oBlock.Data[0:len]
	print "%02x %02x %02x %02x # " % oBlock.Data[0:4], 
	print "%02x %02x %02x %02x # " % oDest.Block[0:4], 
	print "%02x %02x %02x %02x # " % oBlock.Block[0:4], 
	print "L=%x" % oBlock.IP_Length
	if( oBlock.Data[0] != 0x45 ):
	    return 

	oDest.SendBlock(1)

oLM_OUT_CMD = GseosDecoder.TDecoder('CreateLM',fLM_OUT_CMD,[LM_OUT_CMD])
##FTF_OUT_CMD.Decoders.append(oLM_OUT_CMD)

delta = 0
start = 0
def fTime_Delta( oBlock ):
    global delta, start
    if( delta == 0 ):
	delta = time.time() - oBlock.CurrentTimeSecs 
	start = time.time()

    print "%10.1f %10.1f" % (time.time()-start, time.time() - delta - oBlock.CurrentTimeSecs)

oTime_Delta = GseosMonitor.TMonitor('Time_Delta',fTime_Delta)
## DecStatus_LLORRI_CMD.Monitors.append(oTime_Delta)

def fFAKE_OUT_CMD(oBlock):
	"Generated by FAKE_OUT_CMD"
	oDest = FTF_OUT_CMD
	oDest.Block[:] = oBlock.Block[:]

	## print oBlock.DataLen
	iSwaps = oBlock.DataLen 
	for ick in range(0,iSwaps,4):
	    oDest.Data[ick+0] = oBlock.Data[ick+3]
	    oDest.Data[ick+1] = oBlock.Data[ick+2]
	    oDest.Data[ick+2] = oBlock.Data[ick+1]
	    oDest.Data[ick+3] = oBlock.Data[ick+0]
	oDest.SendBlock(1)

oFAKE_OUT_CMD = GseosDecoder.TDecoder('FAKE OUT',fFAKE_OUT_CMD,[FTF_OUT_CMD])
FTF_OUT_CMD_XXX.Decoders.append(oFAKE_OUT_CMD)


def fFAKE_IN_TLM(oBlock):
	"Generated by FAKE_IN_TLM"
	oDest = TLM_LS_IP
	"""
	print oBlock.Len
	print "%02x " % oBlock.Block[0],
	print "%02x " % oBlock.Block[1],
	print "%02x " % oBlock.Block[2],
	print "%02x " % oBlock.Block[3],
	print "%02x " % oBlock.Block[4],
	print "%02x " % oBlock.Block[5],
	print "%02x " % oBlock.Block[6],
	print "%02x " % oBlock.Block[7]
	"""

	oDest.Len = oBlock.Len 

	iSwaps = oBlock.Len 
	iSwaps = 1024
	for ick in range(0,iSwaps,4):
	    oDest.Block[ick+0] = oBlock.Block[ick+3]
	    oDest.Block[ick+1] = oBlock.Block[ick+2]
	    oDest.Block[ick+2] = oBlock.Block[ick+1]
	    oDest.Block[ick+3] = oBlock.Block[ick+0]

	"""
	print "%02x " % oDest.Block[0],
	print "%02x " % oDest.Block[1],
	print "%02x " % oDest.Block[2],
	print "%02x " % oDest.Block[3]
	"""

	oDest.SendBlock(1)

oFAKE_IN_TLM = GseosDecoder.TDecoder('FAKE IN',fFAKE_IN_TLM,[TLM_LS_IP])
SCE_IN_TLM_LS.Decoders.append(oFAKE_IN_TLM)

